// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: app_settings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAppSettingByKeyTenant = `-- name: GetAppSettingByKeyTenant :one
SELECT id, tenant_id, key, value, is_secret, created_at, updated_at
FROM app_settings
WHERE key = $1 AND tenant_id = $2
LIMIT 1
`

type GetAppSettingByKeyTenantParams struct {
	Key      string      `json:"key"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetAppSettingByKeyTenant(ctx context.Context, arg GetAppSettingByKeyTenantParams) (AppSetting, error) {
	row := q.db.QueryRow(ctx, getAppSettingByKeyTenant, arg.Key, arg.TenantID)
	var i AppSetting
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Key,
		&i.Value,
		&i.IsSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAppSettingGlobal = `-- name: GetAppSettingGlobal :one
SELECT id, tenant_id, key, value, is_secret, created_at, updated_at
FROM app_settings
WHERE key = $1 AND tenant_id IS NULL
LIMIT 1
`

func (q *Queries) GetAppSettingGlobal(ctx context.Context, key string) (AppSetting, error) {
	row := q.db.QueryRow(ctx, getAppSettingGlobal, key)
	var i AppSetting
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Key,
		&i.Value,
		&i.IsSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAppSetting = `-- name: UpsertAppSetting :exec
INSERT INTO app_settings (id, tenant_id, key, value, is_secret)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (key, tenant_id)
DO UPDATE SET value = EXCLUDED.value, is_secret = EXCLUDED.is_secret, updated_at = now()
`

type UpsertAppSettingParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
	Key      string      `json:"key"`
	Value    string      `json:"value"`
	IsSecret bool        `json:"is_secret"`
}

func (q *Queries) UpsertAppSetting(ctx context.Context, arg UpsertAppSettingParams) error {
	_, err := q.db.Exec(ctx, upsertAppSetting,
		arg.ID,
		arg.TenantID,
		arg.Key,
		arg.Value,
		arg.IsSecret,
	)
	return err
}
