// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: auth_identities.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthIdentity = `-- name: CreateAuthIdentity :exec
INSERT INTO auth_identities (id, user_id, tenant_id, email, password_hash)
VALUES ($1, $2, $3, $4, $5)
`

type CreateAuthIdentityParams struct {
	ID           pgtype.UUID `json:"id"`
	UserID       pgtype.UUID `json:"user_id"`
	TenantID     pgtype.UUID `json:"tenant_id"`
	Email        string      `json:"email"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) CreateAuthIdentity(ctx context.Context, arg CreateAuthIdentityParams) error {
	_, err := q.db.Exec(ctx, createAuthIdentity,
		arg.ID,
		arg.UserID,
		arg.TenantID,
		arg.Email,
		arg.PasswordHash,
	)
	return err
}

const getAuthIdentitiesByUser = `-- name: GetAuthIdentitiesByUser :many
SELECT id, user_id, tenant_id, email, password_hash, created_at, updated_at
FROM auth_identities
WHERE user_id = $1
`

func (q *Queries) GetAuthIdentitiesByUser(ctx context.Context, userID pgtype.UUID) ([]AuthIdentity, error) {
	rows, err := q.db.Query(ctx, getAuthIdentitiesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthIdentity
	for rows.Next() {
		var i AuthIdentity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TenantID,
			&i.Email,
			&i.PasswordHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuthIdentityByEmailTenant = `-- name: GetAuthIdentityByEmailTenant :one
SELECT id, user_id, tenant_id, email, password_hash, created_at, updated_at
FROM auth_identities
WHERE tenant_id = $1 AND email = $2
`

type GetAuthIdentityByEmailTenantParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Email    string      `json:"email"`
}

func (q *Queries) GetAuthIdentityByEmailTenant(ctx context.Context, arg GetAuthIdentityByEmailTenantParams) (AuthIdentity, error) {
	row := q.db.QueryRow(ctx, getAuthIdentityByEmailTenant, arg.TenantID, arg.Email)
	var i AuthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAuthIdentityPassword = `-- name: UpdateAuthIdentityPassword :exec
UPDATE auth_identities
SET password_hash = $2, updated_at = now()
WHERE id = $1
`

type UpdateAuthIdentityPasswordParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) UpdateAuthIdentityPassword(ctx context.Context, arg UpdateAuthIdentityPasswordParams) error {
	_, err := q.db.Exec(ctx, updateAuthIdentityPassword, arg.ID, arg.PasswordHash)
	return err
}
