// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth_identities.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthIdentity = `-- name: CreateAuthIdentity :exec
INSERT INTO auth_identities (id, user_id, tenant_id, email, password_hash)
VALUES ($1, $2, $3, $4, $5)
`

type CreateAuthIdentityParams struct {
	ID           pgtype.UUID `json:"id"`
	UserID       pgtype.UUID `json:"user_id"`
	TenantID     pgtype.UUID `json:"tenant_id"`
	Email        string      `json:"email"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) CreateAuthIdentity(ctx context.Context, arg CreateAuthIdentityParams) error {
	_, err := q.db.Exec(ctx, createAuthIdentity,
		arg.ID,
		arg.UserID,
		arg.TenantID,
		arg.Email,
		arg.PasswordHash,
	)
	return err
}

const createSSOIdentity = `-- name: CreateSSOIdentity :one

INSERT INTO auth_identities (id, user_id, tenant_id, email, sso_provider_id, sso_subject, sso_attributes)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, tenant_id, email, password_hash, created_at, updated_at, sso_provider_id, sso_subject, sso_attributes
`

type CreateSSOIdentityParams struct {
	ID            pgtype.UUID `json:"id"`
	UserID        pgtype.UUID `json:"user_id"`
	TenantID      pgtype.UUID `json:"tenant_id"`
	Email         string      `json:"email"`
	SsoProviderID pgtype.UUID `json:"sso_provider_id"`
	SsoSubject    pgtype.Text `json:"sso_subject"`
	SsoAttributes []byte      `json:"sso_attributes"`
}

// SSO Identity Management
func (q *Queries) CreateSSOIdentity(ctx context.Context, arg CreateSSOIdentityParams) (AuthIdentity, error) {
	row := q.db.QueryRow(ctx, createSSOIdentity,
		arg.ID,
		arg.UserID,
		arg.TenantID,
		arg.Email,
		arg.SsoProviderID,
		arg.SsoSubject,
		arg.SsoAttributes,
	)
	var i AuthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SsoProviderID,
		&i.SsoSubject,
		&i.SsoAttributes,
	)
	return i, err
}

const getAuthIdentitiesByUser = `-- name: GetAuthIdentitiesByUser :many
SELECT id, user_id, tenant_id, email, password_hash, created_at, updated_at, sso_provider_id, sso_subject, sso_attributes
FROM auth_identities
WHERE user_id = $1
`

func (q *Queries) GetAuthIdentitiesByUser(ctx context.Context, userID pgtype.UUID) ([]AuthIdentity, error) {
	rows, err := q.db.Query(ctx, getAuthIdentitiesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthIdentity
	for rows.Next() {
		var i AuthIdentity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TenantID,
			&i.Email,
			&i.PasswordHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SsoProviderID,
			&i.SsoSubject,
			&i.SsoAttributes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuthIdentityByEmailTenant = `-- name: GetAuthIdentityByEmailTenant :one
SELECT id, user_id, tenant_id, email, password_hash, created_at, updated_at, sso_provider_id, sso_subject, sso_attributes
FROM auth_identities
WHERE tenant_id = $1 AND email = $2
`

type GetAuthIdentityByEmailTenantParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Email    string      `json:"email"`
}

func (q *Queries) GetAuthIdentityByEmailTenant(ctx context.Context, arg GetAuthIdentityByEmailTenantParams) (AuthIdentity, error) {
	row := q.db.QueryRow(ctx, getAuthIdentityByEmailTenant, arg.TenantID, arg.Email)
	var i AuthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SsoProviderID,
		&i.SsoSubject,
		&i.SsoAttributes,
	)
	return i, err
}

const getSSOIdentity = `-- name: GetSSOIdentity :one
SELECT id, user_id, tenant_id, email, password_hash, created_at, updated_at, sso_provider_id, sso_subject, sso_attributes
FROM auth_identities
WHERE tenant_id = $1 AND sso_provider_id = $2 AND sso_subject = $3
`

type GetSSOIdentityParams struct {
	TenantID      pgtype.UUID `json:"tenant_id"`
	SsoProviderID pgtype.UUID `json:"sso_provider_id"`
	SsoSubject    pgtype.Text `json:"sso_subject"`
}

func (q *Queries) GetSSOIdentity(ctx context.Context, arg GetSSOIdentityParams) (AuthIdentity, error) {
	row := q.db.QueryRow(ctx, getSSOIdentity, arg.TenantID, arg.SsoProviderID, arg.SsoSubject)
	var i AuthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SsoProviderID,
		&i.SsoSubject,
		&i.SsoAttributes,
	)
	return i, err
}

const listUserSSOIdentities = `-- name: ListUserSSOIdentities :many
SELECT id, user_id, tenant_id, email, password_hash, created_at, updated_at, sso_provider_id, sso_subject, sso_attributes
FROM auth_identities
WHERE user_id = $1 AND sso_provider_id IS NOT NULL
`

func (q *Queries) ListUserSSOIdentities(ctx context.Context, userID pgtype.UUID) ([]AuthIdentity, error) {
	rows, err := q.db.Query(ctx, listUserSSOIdentities, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthIdentity
	for rows.Next() {
		var i AuthIdentity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TenantID,
			&i.Email,
			&i.PasswordHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SsoProviderID,
			&i.SsoSubject,
			&i.SsoAttributes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlinkSSOIdentity = `-- name: UnlinkSSOIdentity :exec
DELETE FROM auth_identities
WHERE id = $1
`

func (q *Queries) UnlinkSSOIdentity(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, unlinkSSOIdentity, id)
	return err
}

const updateAuthIdentityPassword = `-- name: UpdateAuthIdentityPassword :exec
UPDATE auth_identities
SET password_hash = $2, updated_at = now()
WHERE id = $1
`

type UpdateAuthIdentityPasswordParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) UpdateAuthIdentityPassword(ctx context.Context, arg UpdateAuthIdentityPasswordParams) error {
	_, err := q.db.Exec(ctx, updateAuthIdentityPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateSSOIdentity = `-- name: UpdateSSOIdentity :exec
UPDATE auth_identities
SET sso_attributes = $2, updated_at = now()
WHERE id = $1
`

type UpdateSSOIdentityParams struct {
	ID            pgtype.UUID `json:"id"`
	SsoAttributes []byte      `json:"sso_attributes"`
}

func (q *Queries) UpdateSSOIdentity(ctx context.Context, arg UpdateSSOIdentityParams) error {
	_, err := q.db.Exec(ctx, updateSSOIdentity, arg.ID, arg.SsoAttributes)
	return err
}
