// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth_identities.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthIdentity = `-- name: CreateAuthIdentity :exec
INSERT INTO auth_identities (id, user_id, tenant_id, email, password_hash)
VALUES ($1, $2, $3, $4, $5)
`

type CreateAuthIdentityParams struct {
	ID           pgtype.UUID `json:"id"`
	UserID       pgtype.UUID `json:"user_id"`
	TenantID     pgtype.UUID `json:"tenant_id"`
	Email        string      `json:"email"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) CreateAuthIdentity(ctx context.Context, arg CreateAuthIdentityParams) error {
	_, err := q.db.Exec(ctx, createAuthIdentity,
		arg.ID,
		arg.UserID,
		arg.TenantID,
		arg.Email,
		arg.PasswordHash,
	)
	return err
}

const createSSOIdentity = `-- name: CreateSSOIdentity :one

INSERT INTO auth_identities (id, user_id, tenant_id, email, sso_provider_id, sso_subject, sso_attributes)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, tenant_id, email, password_hash, sso_provider_id, sso_subject, sso_attributes, created_at, updated_at
`

type CreateSSOIdentityParams struct {
	ID            pgtype.UUID `json:"id"`
	UserID        pgtype.UUID `json:"user_id"`
	TenantID      pgtype.UUID `json:"tenant_id"`
	Email         string      `json:"email"`
	SsoProviderID pgtype.UUID `json:"sso_provider_id"`
	SsoSubject    pgtype.Text `json:"sso_subject"`
	SsoAttributes []byte      `json:"sso_attributes"`
}

type CreateSSOIdentityRow struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	Email         string             `json:"email"`
	PasswordHash  pgtype.Text        `json:"password_hash"`
	SsoProviderID pgtype.UUID        `json:"sso_provider_id"`
	SsoSubject    pgtype.Text        `json:"sso_subject"`
	SsoAttributes []byte             `json:"sso_attributes"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

// SSO Identity Management
func (q *Queries) CreateSSOIdentity(ctx context.Context, arg CreateSSOIdentityParams) (CreateSSOIdentityRow, error) {
	row := q.db.QueryRow(ctx, createSSOIdentity,
		arg.ID,
		arg.UserID,
		arg.TenantID,
		arg.Email,
		arg.SsoProviderID,
		arg.SsoSubject,
		arg.SsoAttributes,
	)
	var i CreateSSOIdentityRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.SsoProviderID,
		&i.SsoSubject,
		&i.SsoAttributes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuthIdentitiesByUser = `-- name: GetAuthIdentitiesByUser :many
SELECT id, user_id, tenant_id, email, password_hash, sso_provider_id, sso_subject, sso_attributes, created_at, updated_at
FROM auth_identities
WHERE user_id = $1
`

type GetAuthIdentitiesByUserRow struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	Email         string             `json:"email"`
	PasswordHash  pgtype.Text        `json:"password_hash"`
	SsoProviderID pgtype.UUID        `json:"sso_provider_id"`
	SsoSubject    pgtype.Text        `json:"sso_subject"`
	SsoAttributes []byte             `json:"sso_attributes"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetAuthIdentitiesByUser(ctx context.Context, userID pgtype.UUID) ([]GetAuthIdentitiesByUserRow, error) {
	rows, err := q.db.Query(ctx, getAuthIdentitiesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAuthIdentitiesByUserRow
	for rows.Next() {
		var i GetAuthIdentitiesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TenantID,
			&i.Email,
			&i.PasswordHash,
			&i.SsoProviderID,
			&i.SsoSubject,
			&i.SsoAttributes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuthIdentitiesByUserForUpdate = `-- name: GetAuthIdentitiesByUserForUpdate :many
SELECT id, user_id, tenant_id, email, password_hash, sso_provider_id, sso_subject, sso_attributes, created_at, updated_at
FROM auth_identities
WHERE user_id = $1
FOR UPDATE
`

type GetAuthIdentitiesByUserForUpdateRow struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	Email         string             `json:"email"`
	PasswordHash  pgtype.Text        `json:"password_hash"`
	SsoProviderID pgtype.UUID        `json:"sso_provider_id"`
	SsoSubject    pgtype.Text        `json:"sso_subject"`
	SsoAttributes []byte             `json:"sso_attributes"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetAuthIdentitiesByUserForUpdate(ctx context.Context, userID pgtype.UUID) ([]GetAuthIdentitiesByUserForUpdateRow, error) {
	rows, err := q.db.Query(ctx, getAuthIdentitiesByUserForUpdate, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAuthIdentitiesByUserForUpdateRow
	for rows.Next() {
		var i GetAuthIdentitiesByUserForUpdateRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TenantID,
			&i.Email,
			&i.PasswordHash,
			&i.SsoProviderID,
			&i.SsoSubject,
			&i.SsoAttributes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuthIdentityByEmailTenant = `-- name: GetAuthIdentityByEmailTenant :one
SELECT id, user_id, tenant_id, email, password_hash, sso_provider_id, sso_subject, sso_attributes, created_at, updated_at
FROM auth_identities
WHERE tenant_id = $1 AND email = $2
`

type GetAuthIdentityByEmailTenantParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Email    string      `json:"email"`
}

type GetAuthIdentityByEmailTenantRow struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	Email         string             `json:"email"`
	PasswordHash  pgtype.Text        `json:"password_hash"`
	SsoProviderID pgtype.UUID        `json:"sso_provider_id"`
	SsoSubject    pgtype.Text        `json:"sso_subject"`
	SsoAttributes []byte             `json:"sso_attributes"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetAuthIdentityByEmailTenant(ctx context.Context, arg GetAuthIdentityByEmailTenantParams) (GetAuthIdentityByEmailTenantRow, error) {
	row := q.db.QueryRow(ctx, getAuthIdentityByEmailTenant, arg.TenantID, arg.Email)
	var i GetAuthIdentityByEmailTenantRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.SsoProviderID,
		&i.SsoSubject,
		&i.SsoAttributes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSSOIdentity = `-- name: GetSSOIdentity :one
SELECT id, user_id, tenant_id, email, password_hash, sso_provider_id, sso_subject, sso_attributes, created_at, updated_at
FROM auth_identities
WHERE tenant_id = $1 AND sso_provider_id = $2 AND sso_subject = $3
`

type GetSSOIdentityParams struct {
	TenantID      pgtype.UUID `json:"tenant_id"`
	SsoProviderID pgtype.UUID `json:"sso_provider_id"`
	SsoSubject    pgtype.Text `json:"sso_subject"`
}

type GetSSOIdentityRow struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	Email         string             `json:"email"`
	PasswordHash  pgtype.Text        `json:"password_hash"`
	SsoProviderID pgtype.UUID        `json:"sso_provider_id"`
	SsoSubject    pgtype.Text        `json:"sso_subject"`
	SsoAttributes []byte             `json:"sso_attributes"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetSSOIdentity(ctx context.Context, arg GetSSOIdentityParams) (GetSSOIdentityRow, error) {
	row := q.db.QueryRow(ctx, getSSOIdentity, arg.TenantID, arg.SsoProviderID, arg.SsoSubject)
	var i GetSSOIdentityRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.SsoProviderID,
		&i.SsoSubject,
		&i.SsoAttributes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkSSOToExistingIdentity = `-- name: LinkSSOToExistingIdentity :exec
UPDATE auth_identities
SET sso_provider_id = $2, sso_subject = $3, sso_attributes = $4, updated_at = now()
WHERE id = $1
`

type LinkSSOToExistingIdentityParams struct {
	ID            pgtype.UUID `json:"id"`
	SsoProviderID pgtype.UUID `json:"sso_provider_id"`
	SsoSubject    pgtype.Text `json:"sso_subject"`
	SsoAttributes []byte      `json:"sso_attributes"`
}

func (q *Queries) LinkSSOToExistingIdentity(ctx context.Context, arg LinkSSOToExistingIdentityParams) error {
	_, err := q.db.Exec(ctx, linkSSOToExistingIdentity,
		arg.ID,
		arg.SsoProviderID,
		arg.SsoSubject,
		arg.SsoAttributes,
	)
	return err
}

const listUserSSOIdentities = `-- name: ListUserSSOIdentities :many
SELECT id, user_id, tenant_id, email, password_hash, sso_provider_id, sso_subject, sso_attributes, created_at, updated_at
FROM auth_identities
WHERE user_id = $1 AND sso_provider_id IS NOT NULL
`

type ListUserSSOIdentitiesRow struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	Email         string             `json:"email"`
	PasswordHash  pgtype.Text        `json:"password_hash"`
	SsoProviderID pgtype.UUID        `json:"sso_provider_id"`
	SsoSubject    pgtype.Text        `json:"sso_subject"`
	SsoAttributes []byte             `json:"sso_attributes"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListUserSSOIdentities(ctx context.Context, userID pgtype.UUID) ([]ListUserSSOIdentitiesRow, error) {
	rows, err := q.db.Query(ctx, listUserSSOIdentities, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserSSOIdentitiesRow
	for rows.Next() {
		var i ListUserSSOIdentitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TenantID,
			&i.Email,
			&i.PasswordHash,
			&i.SsoProviderID,
			&i.SsoSubject,
			&i.SsoAttributes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlinkSSOIdentity = `-- name: UnlinkSSOIdentity :exec
DELETE FROM auth_identities
WHERE id = $1 AND tenant_id = $2
`

type UnlinkSSOIdentityParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) UnlinkSSOIdentity(ctx context.Context, arg UnlinkSSOIdentityParams) error {
	_, err := q.db.Exec(ctx, unlinkSSOIdentity, arg.ID, arg.TenantID)
	return err
}

const updateAuthIdentityPassword = `-- name: UpdateAuthIdentityPassword :exec
UPDATE auth_identities
SET password_hash = $2, updated_at = now()
WHERE id = $1
`

type UpdateAuthIdentityPasswordParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) UpdateAuthIdentityPassword(ctx context.Context, arg UpdateAuthIdentityPasswordParams) error {
	_, err := q.db.Exec(ctx, updateAuthIdentityPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateSSOIdentity = `-- name: UpdateSSOIdentity :exec
UPDATE auth_identities
SET sso_attributes = $2, updated_at = now()
WHERE id = $1
`

type UpdateSSOIdentityParams struct {
	ID            pgtype.UUID `json:"id"`
	SsoAttributes []byte      `json:"sso_attributes"`
}

func (q *Queries) UpdateSSOIdentity(ctx context.Context, arg UpdateSSOIdentityParams) error {
	_, err := q.db.Exec(ctx, updateSSOIdentity, arg.ID, arg.SsoAttributes)
	return err
}
