// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: email_verifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeEmailVerification = `-- name: ConsumeEmailVerification :exec
UPDATE email_verifications
SET consumed_at = now()
WHERE token_hash = $1 AND consumed_at IS NULL AND expires_at > now()
`

func (q *Queries) ConsumeEmailVerification(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, consumeEmailVerification, tokenHash)
	return err
}

const createEmailVerification = `-- name: CreateEmailVerification :exec
INSERT INTO email_verifications (id, user_id, tenant_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateEmailVerificationParams struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateEmailVerification(ctx context.Context, arg CreateEmailVerificationParams) error {
	_, err := q.db.Exec(ctx, createEmailVerification,
		arg.ID,
		arg.UserID,
		arg.TenantID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const getEmailVerificationByHash = `-- name: GetEmailVerificationByHash :one
SELECT id, user_id, tenant_id, token_hash, created_at, expires_at, consumed_at
FROM email_verifications
WHERE token_hash = $1
`

func (q *Queries) GetEmailVerificationByHash(ctx context.Context, tokenHash string) (EmailVerification, error) {
	row := q.db.QueryRow(ctx, getEmailVerificationByHash, tokenHash)
	var i EmailVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}
