// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: fga.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addGroupMember = `-- name: AddGroupMember :exec
INSERT INTO group_members (group_id, user_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddGroupMemberParams struct {
	GroupID pgtype.UUID `json:"group_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) AddGroupMember(ctx context.Context, arg AddGroupMemberParams) error {
	_, err := q.db.Exec(ctx, addGroupMember, arg.GroupID, arg.UserID)
	return err
}

const createACLTuple = `-- name: CreateACLTuple :one
INSERT INTO acl_tuples (id, tenant_id, subject_type, subject_id, permission_id, object_type, object_id, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, subject_type, subject_id, permission_id, object_type, object_id, created_by, created_at
`

type CreateACLTupleParams struct {
	ID           pgtype.UUID `json:"id"`
	TenantID     pgtype.UUID `json:"tenant_id"`
	SubjectType  string      `json:"subject_type"`
	SubjectID    pgtype.UUID `json:"subject_id"`
	PermissionID pgtype.UUID `json:"permission_id"`
	ObjectType   string      `json:"object_type"`
	ObjectID     pgtype.Text `json:"object_id"`
	CreatedBy    pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateACLTuple(ctx context.Context, arg CreateACLTupleParams) (AclTuple, error) {
	row := q.db.QueryRow(ctx, createACLTuple,
		arg.ID,
		arg.TenantID,
		arg.SubjectType,
		arg.SubjectID,
		arg.PermissionID,
		arg.ObjectType,
		arg.ObjectID,
		arg.CreatedBy,
	)
	var i AclTuple
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SubjectType,
		&i.SubjectID,
		&i.PermissionID,
		&i.ObjectType,
		&i.ObjectID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createGroup = `-- name: CreateGroup :one

INSERT INTO groups (id, tenant_id, name, description)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, name, description, created_at, updated_at
`

type CreateGroupParams struct {
	ID          pgtype.UUID `json:"id"`
	TenantID    pgtype.UUID `json:"tenant_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

// FGA queries: groups, group_members, acl_tuples
func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Description,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteACLTuple = `-- name: DeleteACLTuple :exec
DELETE FROM acl_tuples
WHERE tenant_id = $1
  AND subject_type = $2
  AND subject_id = $3
  AND permission_id = $4
  AND object_type = $5
  AND (object_id IS NOT DISTINCT FROM $6)
`

type DeleteACLTupleParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	SubjectType  string      `json:"subject_type"`
	SubjectID    pgtype.UUID `json:"subject_id"`
	PermissionID pgtype.UUID `json:"permission_id"`
	ObjectType   string      `json:"object_type"`
	ObjectID     pgtype.Text `json:"object_id"`
}

func (q *Queries) DeleteACLTuple(ctx context.Context, arg DeleteACLTupleParams) error {
	_, err := q.db.Exec(ctx, deleteACLTuple,
		arg.TenantID,
		arg.SubjectType,
		arg.SubjectID,
		arg.PermissionID,
		arg.ObjectType,
		arg.ObjectID,
	)
	return err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM groups
WHERE id = $1 AND tenant_id = $2
`

type DeleteGroupParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteGroup(ctx context.Context, arg DeleteGroupParams) error {
	_, err := q.db.Exec(ctx, deleteGroup, arg.ID, arg.TenantID)
	return err
}

const listGroups = `-- name: ListGroups :many
SELECT id, tenant_id, name, description, created_at, updated_at
FROM groups
WHERE tenant_id = $1
ORDER BY name
`

func (q *Queries) ListGroups(ctx context.Context, tenantID pgtype.UUID) ([]Group, error) {
	rows, err := q.db.Query(ctx, listGroups, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeGroupMember = `-- name: RemoveGroupMember :exec
DELETE FROM group_members
WHERE group_id = $1 AND user_id = $2
`

type RemoveGroupMemberParams struct {
	GroupID pgtype.UUID `json:"group_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) error {
	_, err := q.db.Exec(ctx, removeGroupMember, arg.GroupID, arg.UserID)
	return err
}
