// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invitations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptInvitation = `-- name: AcceptInvitation :exec
UPDATE invitations 
SET status = 'accepted', accepted_at = now(), updated_at = now()
WHERE token_hash = $1 AND status = 'pending' AND expires_at > now()
`

func (q *Queries) AcceptInvitation(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, acceptInvitation, tokenHash)
	return err
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO invitations (id, tenant_id, email, token_hash, role, invited_by, status, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, 'pending', $7)
RETURNING id, tenant_id, email, token_hash, role, invited_by, status, expires_at, accepted_at, created_at, updated_at
`

type CreateInvitationParams struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Email     string             `json:"email"`
	TokenHash string             `json:"token_hash"`
	Role      pgtype.Text        `json:"role"`
	InvitedBy pgtype.UUID        `json:"invited_by"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.ID,
		arg.TenantID,
		arg.Email,
		arg.TokenHash,
		arg.Role,
		arg.InvitedBy,
		arg.ExpiresAt,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.TokenHash,
		&i.Role,
		&i.InvitedBy,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteInvitation = `-- name: DeleteInvitation :exec
DELETE FROM invitations WHERE id = $1 AND tenant_id = $2
`

type DeleteInvitationParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteInvitation(ctx context.Context, arg DeleteInvitationParams) error {
	_, err := q.db.Exec(ctx, deleteInvitation, arg.ID, arg.TenantID)
	return err
}

const expireOldInvitations = `-- name: ExpireOldInvitations :exec
UPDATE invitations 
SET status = 'expired', updated_at = now()
WHERE status = 'pending' AND expires_at <= now()
`

func (q *Queries) ExpireOldInvitations(ctx context.Context) error {
	_, err := q.db.Exec(ctx, expireOldInvitations)
	return err
}

const getInvitationByHash = `-- name: GetInvitationByHash :one
SELECT id, tenant_id, email, token_hash, role, invited_by, status, expires_at, accepted_at, created_at, updated_at FROM invitations WHERE token_hash = $1
`

func (q *Queries) GetInvitationByHash(ctx context.Context, tokenHash string) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByHash, tokenHash)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.TokenHash,
		&i.Role,
		&i.InvitedBy,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvitationByID = `-- name: GetInvitationByID :one
SELECT id, tenant_id, email, token_hash, role, invited_by, status, expires_at, accepted_at, created_at, updated_at FROM invitations WHERE id = $1
`

func (q *Queries) GetInvitationByID(ctx context.Context, id pgtype.UUID) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByID, id)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.TokenHash,
		&i.Role,
		&i.InvitedBy,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingInvitationByEmail = `-- name: GetPendingInvitationByEmail :one
SELECT id, tenant_id, email, token_hash, role, invited_by, status, expires_at, accepted_at, created_at, updated_at FROM invitations 
WHERE email = $1 AND tenant_id = $2 AND status = 'pending' AND expires_at > now()
LIMIT 1
`

type GetPendingInvitationByEmailParams struct {
	Email    string      `json:"email"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetPendingInvitationByEmail(ctx context.Context, arg GetPendingInvitationByEmailParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, getPendingInvitationByEmail, arg.Email, arg.TenantID)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.TokenHash,
		&i.Role,
		&i.InvitedBy,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInvitationsByTenant = `-- name: ListInvitationsByTenant :many
SELECT id, tenant_id, email, token_hash, role, invited_by, status, expires_at, accepted_at, created_at, updated_at FROM invitations 
WHERE tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListInvitationsByTenant(ctx context.Context, tenantID pgtype.UUID) ([]Invitation, error) {
	rows, err := q.db.Query(ctx, listInvitationsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invitation
	for rows.Next() {
		var i Invitation
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Email,
			&i.TokenHash,
			&i.Role,
			&i.InvitedBy,
			&i.Status,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingInvitationsByTenant = `-- name: ListPendingInvitationsByTenant :many
SELECT id, tenant_id, email, token_hash, role, invited_by, status, expires_at, accepted_at, created_at, updated_at FROM invitations 
WHERE tenant_id = $1 AND status = 'pending' AND expires_at > now()
ORDER BY created_at DESC
`

func (q *Queries) ListPendingInvitationsByTenant(ctx context.Context, tenantID pgtype.UUID) ([]Invitation, error) {
	rows, err := q.db.Query(ctx, listPendingInvitationsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invitation
	for rows.Next() {
		var i Invitation
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Email,
			&i.TokenHash,
			&i.Role,
			&i.InvitedBy,
			&i.Status,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeInvitation = `-- name: RevokeInvitation :exec
UPDATE invitations 
SET status = 'revoked', updated_at = now()
WHERE id = $1 AND tenant_id = $2
`

type RevokeInvitationParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) RevokeInvitation(ctx context.Context, arg RevokeInvitationParams) error {
	_, err := q.db.Exec(ctx, revokeInvitation, arg.ID, arg.TenantID)
	return err
}
