// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lockout.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLockoutStatus = `-- name: GetLockoutStatus :one
SELECT failed_attempts, locked_until
FROM auth_identities
WHERE tenant_id = $1 AND email = $2
`

type GetLockoutStatusParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Email    string      `json:"email"`
}

type GetLockoutStatusRow struct {
	FailedAttempts int32              `json:"failed_attempts"`
	LockedUntil    pgtype.Timestamptz `json:"locked_until"`
}

func (q *Queries) GetLockoutStatus(ctx context.Context, arg GetLockoutStatusParams) (GetLockoutStatusRow, error) {
	row := q.db.QueryRow(ctx, getLockoutStatus, arg.TenantID, arg.Email)
	var i GetLockoutStatusRow
	err := row.Scan(&i.FailedAttempts, &i.LockedUntil)
	return i, err
}

const incrementFailedAttempts = `-- name: IncrementFailedAttempts :one
UPDATE auth_identities
SET failed_attempts = failed_attempts + 1
WHERE tenant_id = $1 AND email = $2
RETURNING failed_attempts
`

type IncrementFailedAttemptsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Email    string      `json:"email"`
}

func (q *Queries) IncrementFailedAttempts(ctx context.Context, arg IncrementFailedAttemptsParams) (int32, error) {
	row := q.db.QueryRow(ctx, incrementFailedAttempts, arg.TenantID, arg.Email)
	var failed_attempts int32
	err := row.Scan(&failed_attempts)
	return failed_attempts, err
}

const lockAccount = `-- name: LockAccount :exec
UPDATE auth_identities
SET locked_until = $3
WHERE tenant_id = $1 AND email = $2
`

type LockAccountParams struct {
	TenantID    pgtype.UUID        `json:"tenant_id"`
	Email       string             `json:"email"`
	LockedUntil pgtype.Timestamptz `json:"locked_until"`
}

func (q *Queries) LockAccount(ctx context.Context, arg LockAccountParams) error {
	_, err := q.db.Exec(ctx, lockAccount, arg.TenantID, arg.Email, arg.LockedUntil)
	return err
}

const resetFailedAttempts = `-- name: ResetFailedAttempts :exec
UPDATE auth_identities
SET failed_attempts = 0, locked_until = NULL
WHERE tenant_id = $1 AND email = $2
`

type ResetFailedAttemptsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Email    string      `json:"email"`
}

func (q *Queries) ResetFailedAttempts(ctx context.Context, arg ResetFailedAttemptsParams) error {
	_, err := q.db.Exec(ctx, resetFailedAttempts, arg.TenantID, arg.Email)
	return err
}

const unlockAccount = `-- name: UnlockAccount :exec
UPDATE auth_identities
SET failed_attempts = 0, locked_until = NULL
WHERE user_id = $1
`

func (q *Queries) UnlockAccount(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, unlockAccount, userID)
	return err
}
