// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: magic_links.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeMagicLink = `-- name: ConsumeMagicLink :exec
UPDATE magic_links
SET consumed_at = now()
WHERE token_hash = $1 AND consumed_at IS NULL AND expires_at > now()
`

func (q *Queries) ConsumeMagicLink(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, consumeMagicLink, tokenHash)
	return err
}

const createMagicLink = `-- name: CreateMagicLink :exec
INSERT INTO magic_links (id, user_id, tenant_id, email, token_hash, redirect_url, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateMagicLinkParams struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	Email       pgtype.Text        `json:"email"`
	TokenHash   string             `json:"token_hash"`
	RedirectUrl pgtype.Text        `json:"redirect_url"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateMagicLink(ctx context.Context, arg CreateMagicLinkParams) error {
	_, err := q.db.Exec(ctx, createMagicLink,
		arg.ID,
		arg.UserID,
		arg.TenantID,
		arg.Email,
		arg.TokenHash,
		arg.RedirectUrl,
		arg.ExpiresAt,
	)
	return err
}

const getMagicLinkByHash = `-- name: GetMagicLinkByHash :one
SELECT id, user_id, tenant_id, email, token_hash, redirect_url, created_at, expires_at, consumed_at
FROM magic_links
WHERE token_hash = $1
`

func (q *Queries) GetMagicLinkByHash(ctx context.Context, tokenHash string) (MagicLink, error) {
	row := q.db.QueryRow(ctx, getMagicLinkByHash, tokenHash)
	var i MagicLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.Email,
		&i.TokenHash,
		&i.RedirectUrl,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}
