// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: mfa.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeMFABackupCode = `-- name: ConsumeMFABackupCode :one
UPDATE mfa_backup_codes SET consumed_at = now()
WHERE user_id = $1 AND code_hash = $2 AND consumed_at IS NULL
RETURNING id
`

type ConsumeMFABackupCodeParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	CodeHash string      `json:"code_hash"`
}

func (q *Queries) ConsumeMFABackupCode(ctx context.Context, arg ConsumeMFABackupCodeParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, consumeMFABackupCode, arg.UserID, arg.CodeHash)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const countRemainingMFABackupCodes = `-- name: CountRemainingMFABackupCodes :one
SELECT COUNT(*) FROM mfa_backup_codes WHERE user_id = $1 AND consumed_at IS NULL
`

func (q *Queries) CountRemainingMFABackupCodes(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRemainingMFABackupCodes, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getMFASecret = `-- name: GetMFASecret :one
SELECT user_id, secret, enabled, created_at FROM mfa_secrets WHERE user_id = $1
`

func (q *Queries) GetMFASecret(ctx context.Context, userID pgtype.UUID) (MfaSecret, error) {
	row := q.db.QueryRow(ctx, getMFASecret, userID)
	var i MfaSecret
	err := row.Scan(
		&i.UserID,
		&i.Secret,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const insertMFABackupCode = `-- name: InsertMFABackupCode :exec
INSERT INTO mfa_backup_codes (id, user_id, code_hash)
VALUES ($1, $2, $3)
`

type InsertMFABackupCodeParams struct {
	ID       pgtype.UUID `json:"id"`
	UserID   pgtype.UUID `json:"user_id"`
	CodeHash string      `json:"code_hash"`
}

func (q *Queries) InsertMFABackupCode(ctx context.Context, arg InsertMFABackupCodeParams) error {
	_, err := q.db.Exec(ctx, insertMFABackupCode, arg.ID, arg.UserID, arg.CodeHash)
	return err
}

const upsertMFASecret = `-- name: UpsertMFASecret :exec
INSERT INTO mfa_secrets (user_id, secret, enabled)
VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO UPDATE SET secret = EXCLUDED.secret, enabled = EXCLUDED.enabled
`

type UpsertMFASecretParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Secret  string      `json:"secret"`
	Enabled bool        `json:"enabled"`
}

func (q *Queries) UpsertMFASecret(ctx context.Context, arg UpsertMFASecretParams) error {
	_, err := q.db.Exec(ctx, upsertMFASecret, arg.UserID, arg.Secret, arg.Enabled)
	return err
}
