// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AclTuple struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	SubjectType  string             `json:"subject_type"`
	SubjectID    pgtype.UUID        `json:"subject_id"`
	PermissionID pgtype.UUID        `json:"permission_id"`
	ObjectType   string             `json:"object_type"`
	ObjectID     pgtype.Text        `json:"object_id"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type AppSetting struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Key       string             `json:"key"`
	Value     string             `json:"value"`
	IsSecret  bool               `json:"is_secret"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type AuditLog struct {
	ID        int64              `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Action    string             `json:"action"`
	Metadata  []byte             `json:"metadata"`
	Ip        pgtype.Text        `json:"ip"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type AuthIdentity struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	Email         string             `json:"email"`
	PasswordHash  pgtype.Text        `json:"password_hash"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	SsoProviderID pgtype.UUID        `json:"sso_provider_id"`
	SsoSubject    pgtype.Text        `json:"sso_subject"`
	SsoAttributes []byte             `json:"sso_attributes"`
}

type EmailVerification struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	TokenHash  string             `json:"token_hash"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
}

type Group struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type GroupMember struct {
	GroupID   pgtype.UUID        `json:"group_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type MagicLink struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	Email       pgtype.Text        `json:"email"`
	TokenHash   string             `json:"token_hash"`
	RedirectUrl pgtype.Text        `json:"redirect_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt  pgtype.Timestamptz `json:"consumed_at"`
}

type MfaBackupCode struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	CodeHash   string             `json:"code_hash"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type MfaSecret struct {
	UserID    pgtype.UUID        `json:"user_id"`
	Secret    string             `json:"secret"`
	Enabled   bool               `json:"enabled"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PasswordResetToken struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	Email      string             `json:"email"`
	TokenHash  string             `json:"token_hash"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
}

type Permission struct {
	ID          pgtype.UUID        `json:"id"`
	Key         string             `json:"key"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type RefreshToken struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	TokenHash     string             `json:"token_hash"`
	ParentID      pgtype.UUID        `json:"parent_id"`
	Revoked       bool               `json:"revoked"`
	UserAgent     pgtype.Text        `json:"user_agent"`
	Ip            pgtype.Text        `json:"ip"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	AuthMethod    pgtype.Text        `json:"auth_method"`
	SsoProviderID pgtype.UUID        `json:"sso_provider_id"`
	Metadata      []byte             `json:"metadata"`
}

type Role struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type RolePermission struct {
	RoleID       pgtype.UUID        `json:"role_id"`
	PermissionID pgtype.UUID        `json:"permission_id"`
	ScopeType    string             `json:"scope_type"`
	ResourceType pgtype.Text        `json:"resource_type"`
	ResourceID   pgtype.Text        `json:"resource_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type SsoAuthAttempt struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	ProviderID   pgtype.UUID        `json:"provider_id"`
	UserID       pgtype.UUID        `json:"user_id"`
	State        pgtype.Text        `json:"state"`
	Status       string             `json:"status"`
	ErrorCode    pgtype.Text        `json:"error_code"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	IpAddress    *netip.Addr        `json:"ip_address"`
	UserAgent    pgtype.Text        `json:"user_agent"`
	InitiatedAt  pgtype.Timestamptz `json:"initiated_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
}

type SsoPortalToken struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	SsoProviderID pgtype.UUID        `json:"sso_provider_id"`
	ProviderSlug  string             `json:"provider_slug"`
	TokenHash     string             `json:"token_hash"`
	Intent        string             `json:"intent"`
	CreatedBy     pgtype.UUID        `json:"created_by"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	RevokedAt     pgtype.Timestamptz `json:"revoked_at"`
	MaxUses       int32              `json:"max_uses"`
	UseCount      int32              `json:"use_count"`
	LastUsedAt    pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type SsoProvider struct {
	ID                     pgtype.UUID        `json:"id"`
	TenantID               pgtype.UUID        `json:"tenant_id"`
	Name                   string             `json:"name"`
	Slug                   string             `json:"slug"`
	ProviderType           string             `json:"provider_type"`
	Issuer                 pgtype.Text        `json:"issuer"`
	AuthorizationEndpoint  pgtype.Text        `json:"authorization_endpoint"`
	TokenEndpoint          pgtype.Text        `json:"token_endpoint"`
	UserinfoEndpoint       pgtype.Text        `json:"userinfo_endpoint"`
	JwksUri                pgtype.Text        `json:"jwks_uri"`
	ClientID               pgtype.Text        `json:"client_id"`
	ClientSecret           pgtype.Text        `json:"client_secret"`
	Scopes                 []string           `json:"scopes"`
	ResponseType           pgtype.Text        `json:"response_type"`
	ResponseMode           pgtype.Text        `json:"response_mode"`
	EntityID               pgtype.Text        `json:"entity_id"`
	AcsUrl                 pgtype.Text        `json:"acs_url"`
	SloUrl                 pgtype.Text        `json:"slo_url"`
	IdpMetadataUrl         pgtype.Text        `json:"idp_metadata_url"`
	IdpMetadataXml         pgtype.Text        `json:"idp_metadata_xml"`
	IdpEntityID            pgtype.Text        `json:"idp_entity_id"`
	IdpSsoUrl              pgtype.Text        `json:"idp_sso_url"`
	IdpSloUrl              pgtype.Text        `json:"idp_slo_url"`
	IdpCertificate         pgtype.Text        `json:"idp_certificate"`
	SpCertificate          pgtype.Text        `json:"sp_certificate"`
	SpPrivateKey           pgtype.Text        `json:"sp_private_key"`
	SpCertificateExpiresAt pgtype.Timestamptz `json:"sp_certificate_expires_at"`
	WantAssertionsSigned   pgtype.Bool        `json:"want_assertions_signed"`
	WantResponseSigned     pgtype.Bool        `json:"want_response_signed"`
	SignRequests           pgtype.Bool        `json:"sign_requests"`
	ForceAuthn             pgtype.Bool        `json:"force_authn"`
	AttributeMapping       []byte             `json:"attribute_mapping"`
	Enabled                pgtype.Bool        `json:"enabled"`
	AllowSignup            pgtype.Bool        `json:"allow_signup"`
	TrustEmailVerified     pgtype.Bool        `json:"trust_email_verified"`
	Domains                []string           `json:"domains"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	CreatedBy              pgtype.UUID        `json:"created_by"`
	UpdatedBy              pgtype.UUID        `json:"updated_by"`
	AllowIdpInitiated      pgtype.Bool        `json:"allow_idp_initiated"`
	// Account linking policy: never (no linking), verified_email (link if both emails verified), always (always link - less secure)
	LinkingPolicy pgtype.Text `json:"linking_policy"`
}

type SsoSession struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	ProviderID   pgtype.UUID        `json:"provider_id"`
	UserID       pgtype.UUID        `json:"user_id"`
	SessionIndex pgtype.Text        `json:"session_index"`
	NameID       pgtype.Text        `json:"name_id"`
	IDTokenHint  pgtype.Text        `json:"id_token_hint"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	TerminatedAt pgtype.Timestamptz `json:"terminated_at"`
}

type Tenant struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	IsActive       bool               `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ParentTenantID pgtype.UUID        `json:"parent_tenant_id"`
}

type User struct {
	ID            pgtype.UUID        `json:"id"`
	EmailVerified bool               `json:"email_verified"`
	IsActive      bool               `json:"is_active"`
	FirstName     pgtype.Text        `json:"first_name"`
	LastName      pgtype.Text        `json:"last_name"`
	Roles         []string           `json:"roles"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	LastLoginAt   pgtype.Timestamptz `json:"last_login_at"`
}

type UserRole struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	RoleID    pgtype.UUID        `json:"role_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type UserTenant struct {
	UserID   pgtype.UUID `json:"user_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}
