// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oauth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupExpiredOAuthCodes = `-- name: CleanupExpiredOAuthCodes :exec
DELETE FROM oauth_authorization_codes
WHERE expires_at < now() - INTERVAL '1 hour'
`

func (q *Queries) CleanupExpiredOAuthCodes(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupExpiredOAuthCodes)
	return err
}

const consumeOAuthAuthorizationCode = `-- name: ConsumeOAuthAuthorizationCode :exec
UPDATE oauth_authorization_codes
SET consumed_at = now()
WHERE code_hash = $1 AND consumed_at IS NULL
`

func (q *Queries) ConsumeOAuthAuthorizationCode(ctx context.Context, codeHash string) (int64, error) {
	result, err := q.db.Exec(ctx, consumeOAuthAuthorizationCode, codeHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createOAuthAuthorizationCode = `-- name: CreateOAuthAuthorizationCode :one
INSERT INTO oauth_authorization_codes (
    id, client_id, user_id, tenant_id, code_hash,
    redirect_uri, scopes, nonce, code_challenge, code_challenge_method,
    expires_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11
) RETURNING id, client_id, user_id, tenant_id, code_hash, redirect_uri, scopes, nonce, code_challenge, code_challenge_method, expires_at, consumed_at, created_at
`

type CreateOAuthAuthorizationCodeParams struct {
	ID                  pgtype.UUID        `json:"id"`
	ClientID            string             `json:"client_id"`
	UserID              pgtype.UUID        `json:"user_id"`
	TenantID            pgtype.UUID        `json:"tenant_id"`
	CodeHash            string             `json:"code_hash"`
	RedirectUri         string             `json:"redirect_uri"`
	Scopes              []string           `json:"scopes"`
	Nonce               pgtype.Text        `json:"nonce"`
	CodeChallenge       pgtype.Text        `json:"code_challenge"`
	CodeChallengeMethod pgtype.Text        `json:"code_challenge_method"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateOAuthAuthorizationCode(ctx context.Context, arg CreateOAuthAuthorizationCodeParams) (OauthAuthorizationCode, error) {
	row := q.db.QueryRow(ctx, createOAuthAuthorizationCode,
		arg.ID,
		arg.ClientID,
		arg.UserID,
		arg.TenantID,
		arg.CodeHash,
		arg.RedirectUri,
		arg.Scopes,
		arg.Nonce,
		arg.CodeChallenge,
		arg.CodeChallengeMethod,
		arg.ExpiresAt,
	)
	var i OauthAuthorizationCode
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.UserID,
		&i.TenantID,
		&i.CodeHash,
		&i.RedirectUri,
		&i.Scopes,
		&i.Nonce,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createOAuthClient = `-- name: CreateOAuthClient :one
INSERT INTO oauth_clients (
    id, tenant_id, client_id, client_secret_hash, client_type,
    name, redirect_uris, scopes, grant_types, logo_uri, created_by
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10, $11
) RETURNING id, tenant_id, client_id, client_secret_hash, client_type, name, redirect_uris, scopes, grant_types, logo_uri, is_active, created_by, created_at, updated_at, application_id
`

type CreateOAuthClientParams struct {
	ID               pgtype.UUID `json:"id"`
	TenantID         pgtype.UUID `json:"tenant_id"`
	ClientID         string      `json:"client_id"`
	ClientSecretHash pgtype.Text `json:"client_secret_hash"`
	ClientType       string      `json:"client_type"`
	Name             string      `json:"name"`
	RedirectUris     []string    `json:"redirect_uris"`
	Scopes           []string    `json:"scopes"`
	GrantTypes       []string    `json:"grant_types"`
	LogoUri          pgtype.Text `json:"logo_uri"`
	CreatedBy        pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateOAuthClient(ctx context.Context, arg CreateOAuthClientParams) (OauthClient, error) {
	row := q.db.QueryRow(ctx, createOAuthClient,
		arg.ID,
		arg.TenantID,
		arg.ClientID,
		arg.ClientSecretHash,
		arg.ClientType,
		arg.Name,
		arg.RedirectUris,
		arg.Scopes,
		arg.GrantTypes,
		arg.LogoUri,
		arg.CreatedBy,
	)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientID,
		&i.ClientSecretHash,
		&i.ClientType,
		&i.Name,
		&i.RedirectUris,
		&i.Scopes,
		&i.GrantTypes,
		&i.LogoUri,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ApplicationID,
	)
	return i, err
}

const deleteOAuthClient = `-- name: DeleteOAuthClient :exec
DELETE FROM oauth_clients
WHERE id = $1 AND tenant_id = $2
`

type DeleteOAuthClientParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteOAuthClient(ctx context.Context, arg DeleteOAuthClientParams) error {
	_, err := q.db.Exec(ctx, deleteOAuthClient, arg.ID, arg.TenantID)
	return err
}

const getOAuthAuthorizationCodeByHash = `-- name: GetOAuthAuthorizationCodeByHash :one
SELECT id, client_id, user_id, tenant_id, code_hash, redirect_uri, scopes, nonce, code_challenge, code_challenge_method, expires_at, consumed_at, created_at FROM oauth_authorization_codes
WHERE code_hash = $1 AND consumed_at IS NULL AND expires_at > now()
`

func (q *Queries) GetOAuthAuthorizationCodeByHash(ctx context.Context, codeHash string) (OauthAuthorizationCode, error) {
	row := q.db.QueryRow(ctx, getOAuthAuthorizationCodeByHash, codeHash)
	var i OauthAuthorizationCode
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.UserID,
		&i.TenantID,
		&i.CodeHash,
		&i.RedirectUri,
		&i.Scopes,
		&i.Nonce,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getOAuthClientByClientID = `-- name: GetOAuthClientByClientID :one
SELECT id, tenant_id, client_id, client_secret_hash, client_type, name, redirect_uris, scopes, grant_types, logo_uri, is_active, created_by, created_at, updated_at, application_id FROM oauth_clients
WHERE client_id = $1 AND is_active = TRUE
`

func (q *Queries) GetOAuthClientByClientID(ctx context.Context, clientID string) (OauthClient, error) {
	row := q.db.QueryRow(ctx, getOAuthClientByClientID, clientID)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientID,
		&i.ClientSecretHash,
		&i.ClientType,
		&i.Name,
		&i.RedirectUris,
		&i.Scopes,
		&i.GrantTypes,
		&i.LogoUri,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ApplicationID,
	)
	return i, err
}

const getOAuthClientByID = `-- name: GetOAuthClientByID :one
SELECT id, tenant_id, client_id, client_secret_hash, client_type, name, redirect_uris, scopes, grant_types, logo_uri, is_active, created_by, created_at, updated_at, application_id FROM oauth_clients
WHERE id = $1 AND tenant_id = $2
`

type GetOAuthClientByIDParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetOAuthClientByID(ctx context.Context, arg GetOAuthClientByIDParams) (OauthClient, error) {
	row := q.db.QueryRow(ctx, getOAuthClientByID, arg.ID, arg.TenantID)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientID,
		&i.ClientSecretHash,
		&i.ClientType,
		&i.Name,
		&i.RedirectUris,
		&i.Scopes,
		&i.GrantTypes,
		&i.LogoUri,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ApplicationID,
	)
	return i, err
}

const getOAuthConsentGrant = `-- name: GetOAuthConsentGrant :one
SELECT id, user_id, tenant_id, client_id, scopes, granted_at, revoked_at FROM oauth_consent_grants
WHERE user_id = $1 AND client_id = $2 AND tenant_id = $3 AND revoked_at IS NULL
`

type GetOAuthConsentGrantParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	ClientID string      `json:"client_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetOAuthConsentGrant(ctx context.Context, arg GetOAuthConsentGrantParams) (OauthConsentGrant, error) {
	row := q.db.QueryRow(ctx, getOAuthConsentGrant, arg.UserID, arg.ClientID, arg.TenantID)
	var i OauthConsentGrant
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.ClientID,
		&i.Scopes,
		&i.GrantedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listOAuthClientsByTenant = `-- name: ListOAuthClientsByTenant :many
SELECT id, tenant_id, client_id, client_secret_hash, client_type, name, redirect_uris, scopes, grant_types, logo_uri, is_active, created_by, created_at, updated_at, application_id FROM oauth_clients
WHERE tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListOAuthClientsByTenant(ctx context.Context, tenantID pgtype.UUID) ([]OauthClient, error) {
	rows, err := q.db.Query(ctx, listOAuthClientsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OauthClient
	for rows.Next() {
		var i OauthClient
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ClientID,
			&i.ClientSecretHash,
			&i.ClientType,
			&i.Name,
			&i.RedirectUris,
			&i.Scopes,
			&i.GrantTypes,
			&i.LogoUri,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ApplicationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeOAuthConsentGrant = `-- name: RevokeOAuthConsentGrant :exec
UPDATE oauth_consent_grants
SET revoked_at = now()
WHERE user_id = $1 AND client_id = $2 AND tenant_id = $3 AND revoked_at IS NULL
`

type RevokeOAuthConsentGrantParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	ClientID string      `json:"client_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) RevokeOAuthConsentGrant(ctx context.Context, arg RevokeOAuthConsentGrantParams) error {
	_, err := q.db.Exec(ctx, revokeOAuthConsentGrant, arg.UserID, arg.ClientID, arg.TenantID)
	return err
}

const updateOAuthClient = `-- name: UpdateOAuthClient :exec
UPDATE oauth_clients
SET name = COALESCE(NULLIF($1::text, ''), name),
    redirect_uris = COALESCE($2, redirect_uris),
    scopes = COALESCE($3, scopes),
    grant_types = COALESCE($4, grant_types),
    logo_uri = COALESCE($5, logo_uri),
    is_active = COALESCE($6, is_active),
    updated_at = now()
WHERE id = $7 AND tenant_id = $8
`

type UpdateOAuthClientParams struct {
	Name         string      `json:"name"`
	RedirectUris []string    `json:"redirect_uris"`
	Scopes       []string    `json:"scopes"`
	GrantTypes   []string    `json:"grant_types"`
	LogoUri      pgtype.Text `json:"logo_uri"`
	IsActive     pgtype.Bool `json:"is_active"`
	ID           pgtype.UUID `json:"id"`
	TenantID     pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) UpdateOAuthClient(ctx context.Context, arg UpdateOAuthClientParams) error {
	_, err := q.db.Exec(ctx, updateOAuthClient,
		arg.Name,
		arg.RedirectUris,
		arg.Scopes,
		arg.GrantTypes,
		arg.LogoUri,
		arg.IsActive,
		arg.ID,
		arg.TenantID,
	)
	return err
}

const upsertOAuthConsentGrant = `-- name: UpsertOAuthConsentGrant :one
INSERT INTO oauth_consent_grants (user_id, tenant_id, client_id, scopes)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, client_id, tenant_id) DO UPDATE
SET scopes = EXCLUDED.scopes, granted_at = now(), revoked_at = NULL
RETURNING id, user_id, tenant_id, client_id, scopes, granted_at, revoked_at
`

type UpsertOAuthConsentGrantParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
	ClientID string      `json:"client_id"`
	Scopes   []string    `json:"scopes"`
}

func (q *Queries) UpsertOAuthConsentGrant(ctx context.Context, arg UpsertOAuthConsentGrantParams) (OauthConsentGrant, error) {
	row := q.db.QueryRow(ctx, upsertOAuthConsentGrant,
		arg.UserID,
		arg.TenantID,
		arg.ClientID,
		arg.Scopes,
	)
	var i OauthConsentGrant
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.ClientID,
		&i.Scopes,
		&i.GrantedAt,
		&i.RevokedAt,
	)
	return i, err
}
