// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: password_reset.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumePasswordResetToken = `-- name: ConsumePasswordResetToken :exec
UPDATE password_reset_tokens
SET consumed_at = now()
WHERE token_hash = $1 AND consumed_at IS NULL AND expires_at > now()
`

func (q *Queries) ConsumePasswordResetToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, consumePasswordResetToken, tokenHash)
	return err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :exec
INSERT INTO password_reset_tokens (id, user_id, tenant_id, email, token_hash, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreatePasswordResetTokenParams struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Email     string             `json:"email"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) error {
	_, err := q.db.Exec(ctx, createPasswordResetToken,
		arg.ID,
		arg.UserID,
		arg.TenantID,
		arg.Email,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const getPasswordResetTokenByHash = `-- name: GetPasswordResetTokenByHash :one
SELECT id, user_id, tenant_id, email, token_hash, created_at, expires_at, consumed_at
FROM password_reset_tokens
WHERE token_hash = $1
`

func (q *Queries) GetPasswordResetTokenByHash(ctx context.Context, tokenHash string) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, getPasswordResetTokenByHash, tokenHash)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.Email,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const updateAuthIdentityPasswordByTenantEmail = `-- name: UpdateAuthIdentityPasswordByTenantEmail :exec
UPDATE auth_identities
SET password_hash = $3, updated_at = now()
WHERE tenant_id = $1 AND email = $2
`

type UpdateAuthIdentityPasswordByTenantEmailParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	Email        string      `json:"email"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) UpdateAuthIdentityPasswordByTenantEmail(ctx context.Context, arg UpdateAuthIdentityPasswordByTenantEmailParams) error {
	_, err := q.db.Exec(ctx, updateAuthIdentityPasswordByTenantEmail, arg.TenantID, arg.Email, arg.PasswordHash)
	return err
}
