// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, tenant_id, token_hash, parent_id, revoked, user_agent, ip, created_at, expires_at, auth_method, sso_provider_id, metadata
FROM refresh_tokens
WHERE token_hash = $1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.TokenHash,
		&i.ParentID,
		&i.Revoked,
		&i.UserAgent,
		&i.Ip,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AuthMethod,
		&i.SsoProviderID,
		&i.Metadata,
	)
	return i, err
}

const insertRefreshToken = `-- name: InsertRefreshToken :exec
INSERT INTO refresh_tokens (id, user_id, tenant_id, token_hash, parent_id, user_agent, ip, expires_at, auth_method, sso_provider_id, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type InsertRefreshTokenParams struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	TokenHash     string             `json:"token_hash"`
	ParentID      pgtype.UUID        `json:"parent_id"`
	UserAgent     pgtype.Text        `json:"user_agent"`
	Ip            pgtype.Text        `json:"ip"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	AuthMethod    pgtype.Text        `json:"auth_method"`
	SsoProviderID pgtype.UUID        `json:"sso_provider_id"`
	Metadata      []byte             `json:"metadata"`
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, insertRefreshToken,
		arg.ID,
		arg.UserID,
		arg.TenantID,
		arg.TokenHash,
		arg.ParentID,
		arg.UserAgent,
		arg.Ip,
		arg.ExpiresAt,
		arg.AuthMethod,
		arg.SsoProviderID,
		arg.Metadata,
	)
	return err
}

const listUserSessions = `-- name: ListUserSessions :many
SELECT rt.id, rt.user_id, rt.tenant_id, rt.token_hash, rt.parent_id, rt.revoked, rt.user_agent, rt.ip, rt.created_at, rt.expires_at, rt.auth_method, rt.sso_provider_id, rt.metadata, sp.name as sso_provider_name, sp.slug as sso_provider_slug
FROM refresh_tokens rt
LEFT JOIN sso_providers sp ON rt.sso_provider_id = sp.id
WHERE rt.user_id = $1 AND rt.tenant_id = $2
ORDER BY rt.created_at DESC
`

type ListUserSessionsParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

type ListUserSessionsRow struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	TenantID        pgtype.UUID        `json:"tenant_id"`
	TokenHash       string             `json:"token_hash"`
	ParentID        pgtype.UUID        `json:"parent_id"`
	Revoked         bool               `json:"revoked"`
	UserAgent       pgtype.Text        `json:"user_agent"`
	Ip              pgtype.Text        `json:"ip"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	AuthMethod      pgtype.Text        `json:"auth_method"`
	SsoProviderID   pgtype.UUID        `json:"sso_provider_id"`
	Metadata        []byte             `json:"metadata"`
	SsoProviderName pgtype.Text        `json:"sso_provider_name"`
	SsoProviderSlug pgtype.Text        `json:"sso_provider_slug"`
}

func (q *Queries) ListUserSessions(ctx context.Context, arg ListUserSessionsParams) ([]ListUserSessionsRow, error) {
	rows, err := q.db.Query(ctx, listUserSessions, arg.UserID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserSessionsRow
	for rows.Next() {
		var i ListUserSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TenantID,
			&i.TokenHash,
			&i.ParentID,
			&i.Revoked,
			&i.UserAgent,
			&i.Ip,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.AuthMethod,
			&i.SsoProviderID,
			&i.Metadata,
			&i.SsoProviderName,
			&i.SsoProviderSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens SET revoked = TRUE WHERE id = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, id)
	return err
}

const revokeRefreshTokenByHash = `-- name: RevokeRefreshTokenByHash :execrows
UPDATE refresh_tokens 
SET revoked = TRUE 
WHERE token_hash = $1 AND revoked = FALSE
`

func (q *Queries) RevokeRefreshTokenByHash(ctx context.Context, tokenHash string) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRefreshTokenByHash, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeRefreshTokensByUserAndTenant = `-- name: RevokeRefreshTokensByUserAndTenant :execrows
UPDATE refresh_tokens 
SET revoked = TRUE 
WHERE user_id = $1 AND tenant_id = $2 AND revoked = FALSE
`

type RevokeRefreshTokensByUserAndTenantParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) RevokeRefreshTokensByUserAndTenant(ctx context.Context, arg RevokeRefreshTokensByUserAndTenantParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRefreshTokensByUserAndTenant, arg.UserID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeTokenChain = `-- name: RevokeTokenChain :exec
WITH RECURSIVE chain AS (
  SELECT rt.id, rt.parent_id FROM refresh_tokens rt WHERE rt.id = $1
  UNION ALL
  SELECT rt.id, rt.parent_id FROM refresh_tokens rt
  JOIN chain c ON rt.parent_id = c.id
)
UPDATE refresh_tokens rt SET revoked = TRUE WHERE rt.id IN (SELECT c.id FROM chain c)
`

func (q *Queries) RevokeTokenChain(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeTokenChain, id)
	return err
}
