// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sso.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSSOIdentity = `-- name: CreateSSOIdentity :exec
INSERT INTO sso_identities (id, provider_id, user_id, external_id)
VALUES ($1, $2, $3, $4)
`

type CreateSSOIdentityParams struct {
	ID         pgtype.UUID `json:"id"`
	ProviderID pgtype.UUID `json:"provider_id"`
	UserID     pgtype.UUID `json:"user_id"`
	ExternalID string      `json:"external_id"`
}

func (q *Queries) CreateSSOIdentity(ctx context.Context, arg CreateSSOIdentityParams) error {
	_, err := q.db.Exec(ctx, createSSOIdentity,
		arg.ID,
		arg.ProviderID,
		arg.UserID,
		arg.ExternalID,
	)
	return err
}

const getSSOIdentity = `-- name: GetSSOIdentity :one
SELECT id, provider_id, user_id, external_id, created_at
FROM sso_identities
WHERE provider_id = $1 AND external_id = $2
`

type GetSSOIdentityParams struct {
	ProviderID pgtype.UUID `json:"provider_id"`
	ExternalID string      `json:"external_id"`
}

func (q *Queries) GetSSOIdentity(ctx context.Context, arg GetSSOIdentityParams) (SsoIdentity, error) {
	row := q.db.QueryRow(ctx, getSSOIdentity, arg.ProviderID, arg.ExternalID)
	var i SsoIdentity
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.UserID,
		&i.ExternalID,
		&i.CreatedAt,
	)
	return i, err
}

const getSSOProvider = `-- name: GetSSOProvider :one
SELECT id, tenant_id, provider, client_id, config, created_at
FROM sso_providers
WHERE tenant_id = $1 AND provider = $2
`

type GetSSOProviderParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Provider string      `json:"provider"`
}

func (q *Queries) GetSSOProvider(ctx context.Context, arg GetSSOProviderParams) (SsoProvider, error) {
	row := q.db.QueryRow(ctx, getSSOProvider, arg.TenantID, arg.Provider)
	var i SsoProvider
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Provider,
		&i.ClientID,
		&i.Config,
		&i.CreatedAt,
	)
	return i, err
}

const upsertSSOProvider = `-- name: UpsertSSOProvider :exec
INSERT INTO sso_providers (id, tenant_id, provider, client_id, config)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (tenant_id, provider) DO UPDATE SET client_id = EXCLUDED.client_id, config = EXCLUDED.config
`

type UpsertSSOProviderParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
	Provider string      `json:"provider"`
	ClientID pgtype.Text `json:"client_id"`
	Config   []byte      `json:"config"`
}

func (q *Queries) UpsertSSOProvider(ctx context.Context, arg UpsertSSOProviderParams) error {
	_, err := q.db.Exec(ctx, upsertSSOProvider,
		arg.ID,
		arg.TenantID,
		arg.Provider,
		arg.ClientID,
		arg.Config,
	)
	return err
}
