// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sso_portal_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeSSOPortalTokenByHash = `-- name: ConsumeSSOPortalTokenByHash :one
UPDATE sso_portal_tokens
SET use_count = use_count + 1,
    last_used_at = NOW()
WHERE token_hash = $1
  AND expires_at > NOW()
  AND revoked_at IS NULL
  AND (max_uses = 0 OR use_count < max_uses)
RETURNING id, tenant_id, sso_provider_id, provider_slug, token_hash, intent, created_by, expires_at, revoked_at, max_uses, use_count, last_used_at, created_at
`

func (q *Queries) ConsumeSSOPortalTokenByHash(ctx context.Context, tokenHash string) (SsoPortalToken, error) {
	row := q.db.QueryRow(ctx, consumeSSOPortalTokenByHash, tokenHash)
	var i SsoPortalToken
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SsoProviderID,
		&i.ProviderSlug,
		&i.TokenHash,
		&i.Intent,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.MaxUses,
		&i.UseCount,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createSSOPortalToken = `-- name: CreateSSOPortalToken :one

INSERT INTO sso_portal_tokens (
    tenant_id,
    sso_provider_id,
    provider_slug,
    token_hash,
    intent,
    created_by,
    expires_at,
    max_uses
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, tenant_id, sso_provider_id, provider_slug, token_hash, intent, created_by, expires_at, revoked_at, max_uses, use_count, last_used_at, created_at
`

type CreateSSOPortalTokenParams struct {
	TenantID      pgtype.UUID        `json:"tenant_id"`
	SsoProviderID pgtype.UUID        `json:"sso_provider_id"`
	ProviderSlug  string             `json:"provider_slug"`
	TokenHash     string             `json:"token_hash"`
	Intent        string             `json:"intent"`
	CreatedBy     pgtype.UUID        `json:"created_by"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	MaxUses       int32              `json:"max_uses"`
}

// SSO Portal Tokens
func (q *Queries) CreateSSOPortalToken(ctx context.Context, arg CreateSSOPortalTokenParams) (SsoPortalToken, error) {
	row := q.db.QueryRow(ctx, createSSOPortalToken,
		arg.TenantID,
		arg.SsoProviderID,
		arg.ProviderSlug,
		arg.TokenHash,
		arg.Intent,
		arg.CreatedBy,
		arg.ExpiresAt,
		arg.MaxUses,
	)
	var i SsoPortalToken
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SsoProviderID,
		&i.ProviderSlug,
		&i.TokenHash,
		&i.Intent,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.MaxUses,
		&i.UseCount,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSSOPortalTokenByHash = `-- name: GetSSOPortalTokenByHash :one
SELECT id, tenant_id, sso_provider_id, provider_slug, token_hash, intent, created_by, expires_at, revoked_at, max_uses, use_count, last_used_at, created_at FROM sso_portal_tokens
WHERE token_hash = $1
  AND expires_at > NOW()
  AND revoked_at IS NULL
`

func (q *Queries) GetSSOPortalTokenByHash(ctx context.Context, tokenHash string) (SsoPortalToken, error) {
	row := q.db.QueryRow(ctx, getSSOPortalTokenByHash, tokenHash)
	var i SsoPortalToken
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SsoProviderID,
		&i.ProviderSlug,
		&i.TokenHash,
		&i.Intent,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.MaxUses,
		&i.UseCount,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeSSOPortalToken = `-- name: RevokeSSOPortalToken :exec
UPDATE sso_portal_tokens
SET revoked_at = NOW()
WHERE id = $1
`

func (q *Queries) RevokeSSOPortalToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeSSOPortalToken, id)
	return err
}
