// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenants.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTenants = `-- name: CountTenants :one
SELECT COUNT(*)
FROM tenants
WHERE ($1::text = '' OR name ILIKE '%' || $1::text || '%')
  AND (
    $2::int = -1 OR
    ($2::int = 1 AND is_active = TRUE) OR
    ($2::int = 0 AND is_active = FALSE)
  )
`

type CountTenantsParams struct {
	Column1 string `json:"column_1"`
	Column2 int32  `json:"column_2"`
}

func (q *Queries) CountTenants(ctx context.Context, arg CountTenantsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTenants, arg.Column1, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTenant = `-- name: CreateTenant :exec
INSERT INTO tenants (id, name)
VALUES ($1, $2)
`

type CreateTenantParams struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) error {
	_, err := q.db.Exec(ctx, createTenant, arg.ID, arg.Name)
	return err
}

const deactivateTenant = `-- name: DeactivateTenant :exec
UPDATE tenants SET is_active = FALSE, updated_at = now()
WHERE id = $1
`

func (q *Queries) DeactivateTenant(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateTenant, id)
	return err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, name, is_active, created_at, updated_at
FROM tenants
WHERE id = $1
`

func (q *Queries) GetTenantByID(ctx context.Context, id pgtype.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantByName = `-- name: GetTenantByName :one
SELECT id, name, is_active, created_at, updated_at
FROM tenants
WHERE name = $1
`

func (q *Queries) GetTenantByName(ctx context.Context, name string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByName, name)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTenants = `-- name: ListTenants :many
SELECT id, name, is_active, created_at, updated_at
FROM tenants
WHERE ($1::text = '' OR name ILIKE '%' || $1::text || '%')
  AND (
    $2::int = -1 OR
    ($2::int = 1 AND is_active = TRUE) OR
    ($2::int = 0 AND is_active = FALSE)
  )
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListTenantsParams struct {
	Column1 string `json:"column_1"`
	Column2 int32  `json:"column_2"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListTenants(ctx context.Context, arg ListTenantsParams) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenants,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tenant
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
