// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_tenants.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addUserToTenant = `-- name: AddUserToTenant :exec
INSERT INTO user_tenants (user_id, tenant_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddUserToTenantParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) AddUserToTenant(ctx context.Context, arg AddUserToTenantParams) error {
	_, err := q.db.Exec(ctx, addUserToTenant, arg.UserID, arg.TenantID)
	return err
}

const listTenantUsers = `-- name: ListTenantUsers :many
SELECT u.id, u.email_verified, u.is_active, u.first_name, u.last_name, u.roles, u.created_at, u.updated_at, u.last_login_at,
       COALESCE(ai.email, '') AS email
FROM user_tenants ut
JOIN users u ON u.id = ut.user_id
LEFT JOIN auth_identities ai ON ai.user_id = u.id AND ai.tenant_id = ut.tenant_id
WHERE ut.tenant_id = $1
`

type ListTenantUsersRow struct {
	ID            pgtype.UUID        `json:"id"`
	EmailVerified bool               `json:"email_verified"`
	IsActive      bool               `json:"is_active"`
	FirstName     pgtype.Text        `json:"first_name"`
	LastName      pgtype.Text        `json:"last_name"`
	Roles         []string           `json:"roles"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	LastLoginAt   pgtype.Timestamptz `json:"last_login_at"`
	Email         string             `json:"email"`
}

func (q *Queries) ListTenantUsers(ctx context.Context, tenantID pgtype.UUID) ([]ListTenantUsersRow, error) {
	rows, err := q.db.Query(ctx, listTenantUsers, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTenantUsersRow
	for rows.Next() {
		var i ListTenantUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.EmailVerified,
			&i.IsActive,
			&i.FirstName,
			&i.LastName,
			&i.Roles,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLoginAt,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTenants = `-- name: ListUserTenants :many
SELECT t.id, t.name, t.is_active, t.created_at, t.updated_at
FROM user_tenants ut
JOIN tenants t ON t.id = ut.tenant_id
WHERE ut.user_id = $1
`

type ListUserTenantsRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListUserTenants(ctx context.Context, userID pgtype.UUID) ([]ListUserTenantsRow, error) {
	rows, err := q.db.Query(ctx, listUserTenants, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserTenantsRow
	for rows.Next() {
		var i ListUserTenantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserFromTenant = `-- name: RemoveUserFromTenant :exec
DELETE FROM user_tenants WHERE user_id = $1 AND tenant_id = $2
`

type RemoveUserFromTenantParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) RemoveUserFromTenant(ctx context.Context, arg RemoveUserFromTenantParams) error {
	_, err := q.db.Exec(ctx, removeUserFromTenant, arg.UserID, arg.TenantID)
	return err
}
