// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, email_verified, is_active, first_name, last_name, roles)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateUserParams struct {
	ID            pgtype.UUID `json:"id"`
	EmailVerified bool        `json:"email_verified"`
	IsActive      bool        `json:"is_active"`
	FirstName     pgtype.Text `json:"first_name"`
	LastName      pgtype.Text `json:"last_name"`
	Roles         []string    `json:"roles"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.EmailVerified,
		arg.IsActive,
		arg.FirstName,
		arg.LastName,
		arg.Roles,
	)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email_verified, is_active, first_name, last_name, roles, created_at, updated_at, last_login_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.EmailVerified,
		&i.IsActive,
		&i.FirstName,
		&i.LastName,
		&i.Roles,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const setUserActive = `-- name: SetUserActive :exec
UPDATE users SET is_active = $2, updated_at = now() WHERE id = $1
`

type SetUserActiveParams struct {
	ID       pgtype.UUID `json:"id"`
	IsActive bool        `json:"is_active"`
}

func (q *Queries) SetUserActive(ctx context.Context, arg SetUserActiveParams) error {
	_, err := q.db.Exec(ctx, setUserActive, arg.ID, arg.IsActive)
	return err
}

const setUserEmailVerified = `-- name: SetUserEmailVerified :exec
UPDATE users SET email_verified = $2, updated_at = now() WHERE id = $1
`

type SetUserEmailVerifiedParams struct {
	ID            pgtype.UUID `json:"id"`
	EmailVerified bool        `json:"email_verified"`
}

func (q *Queries) SetUserEmailVerified(ctx context.Context, arg SetUserEmailVerifiedParams) error {
	_, err := q.db.Exec(ctx, setUserEmailVerified, arg.ID, arg.EmailVerified)
	return err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users SET last_login_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateUserLastLogin, id)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE users SET first_name = $2, last_name = $3, roles = $4, updated_at = now()
WHERE id = $1
`

type UpdateUserProfileParams struct {
	ID        pgtype.UUID `json:"id"`
	FirstName pgtype.Text `json:"first_name"`
	LastName  pgtype.Text `json:"last_name"`
	Roles     []string    `json:"roles"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.Exec(ctx, updateUserProfile,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Roles,
	)
	return err
}
