{{- if .Values.cnpg.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.cnpg.name }}
  labels:
    {{- include "guard-stack.labels" . | nindent 4 }}
spec:
  instances: {{ .Values.cnpg.instances }}

  imageName: {{ .Values.cnpg.imageName }}

  postgresql:
    parameters:
      {{- range $key, $value := .Values.cnpg.postgresql.parameters }}
      {{ $key }}: {{ $value | quote }}
      {{- end }}

  bootstrap:
    initdb:
      database: {{ .Values.database.name }}
      owner: {{ .Values.database.user }}
      secret:
        name: {{ include "guard-stack.secretName" . }}

  storage:
    size: {{ .Values.cnpg.storage.size }}
    {{- if .Values.cnpg.storage.storageClass }}
    storageClass: {{ .Values.cnpg.storage.storageClass }}
    {{- end }}

  {{- with .Values.cnpg.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- if .Values.cnpg.affinity.topologyKey }}
  affinity:
    enablePodAntiAffinity: true
    topologyKey: {{ .Values.cnpg.affinity.topologyKey }}
  {{- end }}

  {{- if .Values.cnpg.backup.enabled }}
  backup:
    barmanObjectStore:
      destinationPath: {{ .Values.cnpg.backup.destinationPath }}
      s3Credentials:
        accessKeyId:
          name: {{ .Values.cnpg.backup.s3CredentialsSecret }}
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: {{ .Values.cnpg.backup.s3CredentialsSecret }}
          key: SECRET_ACCESS_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: {{ .Values.cnpg.backup.retentionPolicy }}
  {{- end }}

  # Monitoring
  monitoring:
    enablePodMonitor: {{ .Values.monitoring.podMonitor.enabled | default .Values.monitoring.serviceMonitor.enabled }}

  # Security
  enableSuperuserAccess: false
{{- end }}
