{{- if .Values.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "guard-stack.fullname" . }}-migration{{- if .Values.migration.hook }}-{{ .Release.Revision }}{{- end }}
  labels:
    {{- include "guard-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: migration
  {{- if .Values.migration.hook }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  {{- end }}
spec:
  {{- if .Values.migration.ttlSecondsAfterFinished }}
  ttlSecondsAfterFinished: {{ .Values.migration.ttlSecondsAfterFinished }}
  {{- end }}
  backoffLimit: {{ .Values.migration.backoffLimit | default 3 }}
  template:
    metadata:
      labels:
        {{- include "guard-stack.labels" . | nindent 8 }}
        app.kubernetes.io/component: migration
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "guard-stack.serviceAccountName" . }}
      restartPolicy: OnFailure
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      initContainers:
        - name: wait-for-db
          image: busybox:1.36
          command: ['sh', '-c']
          args:
            - |
              echo "Waiting for PostgreSQL to be ready..."
              until nc -z {{ include "guard-stack.databaseHost" . }} {{ include "guard-stack.databasePort" . }}; do
                echo "PostgreSQL is not ready yet..."
                sleep 2
              done
              echo "PostgreSQL is ready!"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
        - name: wait-for-redis
          image: busybox:1.36
          command: ['sh', '-c']
          args:
            - >
              echo "Waiting for Valkey to be ready..." ;
              until nc -z {{ printf "%s-valkey-primary" .Release.Name }} 6379; do
                echo "Valkey is not ready yet..." ;
                sleep 2 ;
              done ;
              echo "Valkey is ready!"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
      containers:
        - name: migration
          {{- $migrationImage := .Values.migration.image }}
          {{- if and $migrationImage $migrationImage.repository }}
          image: "{{ $migrationImage.repository }}:{{ $migrationImage.tag | default .Chart.AppVersion }}"
          {{- else }}
          image: {{ include "guard-stack.api.image" . | quote }}
          {{- end }}
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          command: ["guard"]
          args: ["migrate", "up"]
          env:
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "guard-stack.secretName" . }}
                  key: database-password
            - name: DATABASE_URL
              value: {{ include "guard-stack.databaseUrl" . | quote }}
            # Valkey/Redis configuration (match main API deployment)
            - name: REDIS_ADDR
              value: {{ include "guard-stack.valkeyAddr" . | quote }}
            - name: REDIS_DB
              value: {{ include "guard-stack.valkeyDB" . | quote }}
            {{- if or .Values.valkey.enabled (and .Values.externalValkey.addr .Values.secrets.valkeyPassword) }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "guard-stack.secretName" . }}
                  key: valkey-password
            {{- end }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          {{- with .Values.migration.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
