{{- if .Values.networkPolicy.enabled }}
# API Network Policy
{{- if .Values.api.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "guard-stack.api.fullname" . }}
  labels:
    {{- include "guard-stack.api.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "guard-stack.api.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow from ingress controller
    {{- range .Values.networkPolicy.ingressNamespaces }}
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ . }}
      ports:
        - protocol: TCP
          port: 8080
    {{- end }}
    # Allow from UI pods (for internal API calls if needed)
    {{- if .Values.ui.enabled }}
    - from:
        - podSelector:
            matchLabels:
              {{- include "guard-stack.ui.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: 8080
    {{- end }}
    # Allow Prometheus scraping
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - protocol: TCP
          port: 8080
    {{- with .Values.networkPolicy.additionalIngress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  egress:
    # Allow DNS
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    # Allow PostgreSQL (CNPG or external)
    - to:
        - podSelector:
            matchLabels:
              cnpg.io/cluster: {{ .Values.cnpg.name | default "guard-db" }}
      ports:
        - protocol: TCP
          port: 5432
    # Allow external PostgreSQL
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
      ports:
        - protocol: TCP
          port: {{ .Values.database.port | default 5432 }}
    # Allow Valkey
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: valkey
      ports:
        - protocol: TCP
          port: 6379
    # Allow external SMTP (if configured)
    {{- if eq .Values.config.email.provider "smtp" }}
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
      ports:
        - protocol: TCP
          port: {{ .Values.config.email.smtp.port | default 587 }}
        - protocol: TCP
          port: 465
        - protocol: TCP
          port: 25
    {{- end }}
    # Allow external HTTPS (for WorkOS, Brevo, etc.)
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
      ports:
        - protocol: TCP
          port: 443
    {{- with .Values.networkPolicy.additionalEgress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
---
# UI Network Policy
{{- if .Values.ui.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "guard-stack.ui.fullname" . }}
  labels:
    {{- include "guard-stack.ui.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "guard-stack.ui.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow from ingress controller
    {{- range .Values.networkPolicy.ingressNamespaces }}
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ . }}
      ports:
        - protocol: TCP
          port: 80
    {{- end }}
  egress:
    # Allow DNS
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    # UI is static, typically doesn't need egress
    # But allow API access if needed for SSR
    - to:
        - podSelector:
            matchLabels:
              {{- include "guard-stack.api.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: 8080
{{- end }}
{{- end }}
