{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "guard-stack.secretName" . }}
  labels:
    {{- include "guard-stack.labels" . | nindent 4 }}
type: Opaque
data:
  # JWT signing key (required)
  jwt-signing-key: {{ .Values.secrets.jwtSigningKey | b64enc | quote }}
  # Database password (for CNPG or external PostgreSQL)
  database-password: {{ .Values.secrets.databasePassword | b64enc | quote }}
  # Valkey password
  valkey-password: {{ .Values.secrets.valkeyPassword | b64enc | quote }}
  {{- if .Values.secrets.smtpPassword }}
  # SMTP password
  smtp-password: {{ .Values.secrets.smtpPassword | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.brevoApiKey }}
  # Brevo API key
  brevo-api-key: {{ .Values.secrets.brevoApiKey | b64enc | quote }}
  {{- end }}
  {{- if and .Values.secrets.workos.apiKey .Values.secrets.workos.clientId .Values.secrets.workos.clientSecret }}
  # WorkOS credentials
  workos-api-key: {{ .Values.secrets.workos.apiKey | b64enc | quote }}
  workos-client-id: {{ .Values.secrets.workos.clientId | b64enc | quote }}
  workos-client-secret: {{ .Values.secrets.workos.clientSecret | b64enc | quote }}
  {{- end }}
{{- end }}
